owner: timching
repo: upptime

sites:
  # - name: Google
  #   url: https://www.google.com
  # - name: Wikipedia
  #   url: https://en.wikipedia.org
  # - name: Hacker News
  #   url: https://news.ycombinator.com
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co
  - name: BECCAR
    url: https://atelierbeccar.com
  - name: BECCAR (Legacy)
    url: https://beccarcouture.com
  - name: LA CURVE / BECCAR
    url: https://la-curve.com
  # - name: IPv6 test
  #   url: forwardemail.net
  #   port: 80
  #   check: "tcp-ping"
  #   ipv6: true

assignees:
  - timching

status-website:
  baseUrl: /upptime
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
